# Generated by Django 6.0 on 2025-12-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mode', models.CharField(choices=[('visual', 'Visual'), ('audio', 'Audio')], max_length=10)),
                ('round_1', models.IntegerField()),
                ('round_2', models.IntegerField()),
                ('round_3', models.IntegerField()),
                ('round_4', models.IntegerField()),
                ('memory_accuracy', models.FloatField()),
                ('recall_decay_rate', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
